### ISSUE TITLE
Try and Except

### ISSUE THREAD

**Issue by IamSagarRai** [IamSagarRai/Random_Password_Generator#1]
**Hello people !**

Though I have not addressed this issue in the code itself, I have lately realized that what if the user enters something which isn't an integer but a string, it will of course damage the process and would give an error!

But we still can do one thing that is we can use try and except and code it in such a way that instead of abruptly ending the process, the code would specify the user the mistake and tell the thing the user has done wrong and what he/she can do to make it right!

 Thanks for viewing!

**Comment by ShivamRai2003** [comment]
Intrested !
